version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      # - build-and-test
      - aws-code-deploy/deploy:
          application-name: trade-webapp
          bundle-bucket: petercode
          bundle-key: trade-webapp
          deployment-group: pythonapp2
          deployment-config:
            CodeDeployDefault.OneAtATime
            --ignoreApplicationStopFailures
            --ec2-tag-filters Key=Name Value=pythonapp
          service-role-arn: arn:aws:iam::207363230413:role/codedeploy2
          # requires:
          #   - build-and-test  # Only deploy once the build job has completed
          filters:
            branches:
              only: master # Only deploy on the master branch


  